### ISSUE TITLE
[Standards]: Behavior for required fields

### ISSUE THREAD

**Issue by ChristyHermansen** [GSA/sam-web-design-standards#46]
## Additional information [optional]

Looking in the US Web Design Standards and the SAM Web Design Standards, I don't see standard behavior defined for differentiating between required and optional fields.
* Are we marking optional or required fields?  How?

**Comment by jagannathch** [comment]
@ChristyHermansen @joshbruce: I don't mind having a design discussion on this if it makes sense because my opinion on this is "depends" on the specific form being designed. Depends on the number of fields on a form that are required or optional...I have read design books that state that typically if there are many required fields, to indicate the optional ones and vice versa. Happy to discuss this further and come to a consensus on this if needed.

**Comment by joshbruce** [comment]
We do not call it specifically out.

Though there is a CSS class defined is in there: https://standards.usa.gov/form-templates/#name-form

**Comment by joshbruce** [comment]
@ChristyHermansen, and @jagannathch - Forgot to mention. The USWDS does it both ways, dependent on the form, as JC mentions.

https://standards.usa.gov/form-templates/#address-form

**Comment by joshbruce** [comment]
Add language at top of "Form controls" page. Something like:

> If your form consists of all required fields, it is not necessary to mark fields as required or optional. If your form consists of more required fields than optional fields, mark the optional fields, but not the required fields. If your form consists of more optional fields than required, mark the required fields, but not the optional fields.

Think that captures the point, yeah? Thoughts?
